### ISSUE TITLE
When compiling with toolchain, ran out of registers

### ISSUE THREAD

**Issue by ItsSven64** [MathisLav/internetce#8] opened 2023-12-27 14:05 UTC
Title, i get this error
![image](https://github.com/MathisLav/internetce/assets/98273148/5d0cb03f-c5b8-435f-b89b-54d5894f3c24)

Do you know about this?

**Comment by ItsSven64** [comment] 2023-12-27 14:17
After some back and forth with the toolchain team we figured out that it has to do with compiler issues. I added LTO = NO to the makefile, and now it throws the following;
![image](https://github.com/MathisLav/internetce/assets/98273148/ace86e1b-304c-4abc-9ac8-e8a8ad632d0f)

**Comment by ItsSven64** [comment] 2023-12-27 16:31
Thanks for the help! Already opened an issue in toolchain

**Comment by mateoconlechuga** [comment] 2024-01-17 15:00
The issue is the `transport_checksum` function. Changing the `uint16_t chksmmsb` and `uint16_t chksmlsb` variables to be of type `uint24_t` appears to fix the compile issue.

**Comment by MathisLav** [comment] 2024-01-17 15:47
Yes I had this bad habit to always choose the smallest variable size I could use. But I'll release soon a new version that uses uint24_t whenever it's possible, so it should fix the issue.

Thanks for the clarification @mateoconlechuga

**Comment by MathisLav** [comment] 2024-01-23 16:13
Closing the issue as I think the last merge solved it. But feel free to reopen it if you encounter a similar issue again.

**Closed by MathisLav** 2024-01-23 16:13 UTC
